### ISSUE TITLE
A genuine issue. 

### ISSUE THREAD

**Issue by Aniumbott** [Harshil-Jani/wave#1]
Kuchh hume bhi shikha do bhaiya 🙂🙂🙂

**Comment by Harshil-Jani** [comment]
buildspace.so se karlo. Accha hain . Samaj aayega progressively. Aur baki struggle toh hain 1 week mai aur kitna karenge :) 

https://buildspace.so/p/build-solidity-web3-app/lessons/welcome

Bich Bich mai terms GPT ya google karte rehna aur extra sikh lena thoda bahut. Samaj aa jayega. Par confidence nahi ki bina doc chuee Contract likh do. Toh dekhte hain banante hain kuch na kuch. Kabhi toh grip aayegi :)

**Comment by Aniumbott** [comment]
dhanyawad bhai 🤝
